# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#   update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci(provider: "travis")
    match(readonly: true)
    number = sh('date "+%Y.%m.%d.%H%M"')
    increment_build_number(xcodeproj: "COVIDWatch.xcodeproj", build_number: number)
    build_app(workspace: "COVIDWatch.xcworkspace", scheme: "COVIDWatch iOS")
    testflight(skip_waiting_for_build_processing: true, verbose: true, apple_id: "1504929027")
  end
end
