# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#   update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(verbose: true, git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"])
    build_app(workspace: "COVIDWatch.xcworkspace", scheme: "COVIDWatch iOS")
    upload_to_testflight
  end
end
