# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#   update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci(provider: "travis")
    match(readonly: true)
    number = sh('date "+%Y.%m.%d.%H.%M"')
    increment_build_number(xcodeproj: "COVIDWatch.xcodeproj", build_number: number)
    build_app(workspace: "COVIDWatch.xcworkspace", scheme: "covidwatch-ios-prod")
    testflight(apple_id: "1504929027", distribute_external: true, groups: ["Public Link"], changelog: "Daily Beta for " + Date.today.to_s)
  end

  desc "Run UI and Unit Tests"
  lane :tests do
    run_tests(workspace: "COVIDWatch.xcworkspace",
              devices: ["iPhone 11"],
              reinstall_app: true,
              code_coverage: true,
              derived_data_path: "Build",
              scheme: "covidwatch-ios-test")
  end

  desc "Build Only"
  lane :build do
    build_app(workspace: "COVIDWatch.xcworkspace", scheme: "covidwatch-ios-dev", skip_codesigning: true, skip_archive: true)
  end

  desc "SwiftLint"
  lane :lint do
    swiftlint(executable: 'Pods/SwiftLint/swiftlint', strict: true)
  end

  desc "Process Test Coverage Results"
  lane :process_test_coverage do
    slather(proj: "CovidWatch.xcodeproj",
            scheme: "covidwatch-ios-test",
            cobertura_xml: true,
            output_directory: "./coverage",
            build_directory: "./build")
  end
end